plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.yuhj319.banmodifiedsecurityservice'
    compileSdk 34

    defaultConfig {
        applicationId 'io.github.yuhj319.banmodifiedsecurityservice'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
}
